// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/superjcd/calendarservice/conf"
	"github.com/superjcd/calendarservice/genproto/v1"
	"github.com/superjcd/calendarservice/server"
)

// Injectors from wire.go:

// InitServer Inject service's component
func InitServer(conf2 *conf.Config) (v1.CalendarServiceServer, error) {
	calendarServiceClient, err := server.NewClient(conf2)
	if err != nil {
		return nil, err
	}
	calendarServiceServer, err := server.NewServer(conf2, calendarServiceClient)
	if err != nil {
		return nil, err
	}
	return calendarServiceServer, nil
}
